markdown:
  kramdown

baseurl: /grpc.github.io

githuburl: https://github.com/wildebeestdev/grpc.github.io/edit/gh-pages

kramdown:
   input: GFM

sass:
  style: compressed
  
paginate: 2

paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->   

gems:
  - jekyll-sitemap
