markdown:
  kramdown

baseurl: /grpc.github.io

githuburl: https://github.com/wildebeestdev/grpc.github.io/edit/gh-pages

kramdown:
   input: GFM

sass:
  style: compressed
  
excerpt_separator: <!--more-->   
